interface WritingPromptCategory {
  prompts: string[];
}

const writingPrompts: Record<string, WritingPromptCategory> = {
  gratitude: {
    prompts: [
      "It's always important to recognize the little things that make up your life. Can you see any of the 'little things' in your life that you're grateful for?",
      "What is a small comfort you experienced today that made you feel at ease?",
      "Think about someone who made you smile today. What did they do or say?",
      "What is something you love about your life right now?",
      "Is there a sound that brings you comfort or joy? What is it and when did you last hear it?",
      "Reflect on a small act of kindness you either gave or received recently. How did it make you feel?",
      "What’s something you’ve seen recently that brought you peace, even if just for a moment?",
      "Describe a small routine or ritual that brings you a sense of calm or happiness.",
      "Take a moment to appreciate your body. What’s something about it that you’re grateful for today?",
      "Think about a hobby or activity you do just for yourself. How does it make you feel?",
      "What is one thing that you take for granted but are really grateful for when you stop to think about it?",
      "Is there something in nature (even if it's just a small flower or a tree) that made you pause and appreciate it?",
      "When was the last time you laughed so hard it felt good? What sparked that experience?",
      "Reflect on a food or drink that made you feel nourished today. What did it taste like, and how did it make you feel?",
      "Is there a particular smell that brings you comfort? When was the last time you smelled it?",
      "What’s something you’ve learned recently that you’re grateful for, even if it’s small or simple?",
      "Is there a moment recently when you felt truly present and at peace? What was going on?",
      "Can you remember a recent time you felt truly appreciated? What happened, and how did it make you feel?",
      "Have you encountered any small challenges recently that you've handled with more grace than usual? Reflect on that strength.",
      "Think about a small gesture of love or affection you've received recently. How did it make you feel?",
      "Reflect on a time when you felt safe and secure. What made that moment comforting?",
      "What’s one small thing that made you smile today?",
      "What’s something simple that you’ve done recently to take care of yourself?",
      "When was the last time you felt really relaxed? What helped you get to that state?",
      "Think about your favourite place in your home. What makes it feel so special?",
      "What’s a small thing that brightens up your day every time you see it?",
      "What’s something that happened today that you’re grateful for, no matter how minor it may seem?",
      "Have you had a quiet moment today to reflect or pause? Take a moment if need be. What did you appreciate in that silence?",
      "Is there a memory that makes you smile every time you think about it?",
      "Think of something you enjoy doing that helps you reset. How do you feel afterward?",
      "Is there a person or friend you’ve recently reconnected with? What about that made you happy?",
    ],
  },
  "short-story": {
    prompts: [
      "Write a story about everyone in your town forgetting you exist",
      "Write a story about a child’s imaginary friend who is now all grown up",
      "Write a story about a man who discovers his pet goldfish is a crime fighting vigilante",
      "Write a story about a private investigator hired to find a missing person. The twist: The missing person wants to be found, they left a trail of clues for the investigator to follow. You can decide why",
      "Write a story about a superhero whose only power is being able to communicate with inanimate objects. His stuffed pug sidekick has some very strong opinions.",
      "Write a story about the last person on Earth hearing a knock at the door",
      "Write a story about waking up to find your reflection gone",
      "Write a story about a clock that counts down to your last breath starting to tick",
      "Write a story about a door in your house leading to a room that wasn’t there yesterday",
      "Write a story about every mirror you look into showing a different version of yourself",
      "Write a story about a man who goes on a road trip to find closure with an old friend. The twist: The friend isn’t alive anymore, but the journey helps the man come to terms with the unresolved tension between them",
      "Write a story about a place you’ve never been before feeling oddly familiar",
      "Write a story about your dreams starting to bleed into reality",
      "Write a story about your shadow starting to act on its own",
      "Write a story about a garden that grows items instead of plants",
      "Write a story about an elevator that only goes up to places you’ve never been",
      "Write a story about the sun going out for the night and not coming back",
      "Write a story about a library where the books talk back",
    ],
  },
  "self-reflection": {
    prompts: [
      "What’s something you learned about yourself recently?",
      "When was the last time you stepped outside of your comfort zone? How did it feel?",
      "What is one personal strength that has helped you through tough times?",
      "Think about a challenge you’re currently facing. How are you growing from it?",
      "How do you typically respond to stress, and how could you handle it more mindfully?",
      "Reflect on a recent decision you made. What did you learn from that experience?",
      "What does self-care look like for you right now? How does it nourish your mind and body?",
      "What personal values are most important to you? How are you living by them?",
      "How do you celebrate your wins, no matter how small they may seem?",
      "Reflect on a time when you felt proud of yourself. What did you accomplish?",
      "What’s a belief or mindset that’s helped you overcome self-doubt?",
      "Is there something you’re avoiding? What might it be teaching you about yourself?",
      "Think about your relationships: friends, family, romantic, ect. What role do you play in them, and what can you improve?",
      "What’s one habit you’d like to break, and what small steps can you take to start?",
      "What does your inner voice sound like, and how can you make it more supportive?",
      "Reflect on a recent mistake you made. What did it teach you about yourself?",
      "What’s a part of your personality that you admire most?",
      "Think about your goals for the future. How can you align them with your authentic self?",
      "What is one fear you want to overcome, and why is it important to you?",
      "How do you handle criticism, and what can it teach you about your growth?",
      "What does success mean to you? How do you define it on your own terms?",
      "Think about a past version of yourself. What advice would you give them now?",
      "What does it mean to be authentic in your life, and how are you embracing that?",
      "Reflect on a time when you were really in tune with your emotions. What helped you get there?",
      "How do you create balance in your life between work, rest, and play?",
      "What’s one area of your life where you want to grow? What’s the first step you can take?",
      "What does forgiveness look like for you? Is there something you’re holding onto?",
      "Think about a time when you felt at peace with yourself. What helped create that feeling?",
      "What’s a quality you admire in others that you’d like to cultivate more in yourself?",
      "Reflect on how you’ve changed in the past year. What personal growth stands out most?",
    ],
  },
  "philosophical-nonsense": {
    prompts: [
      "Do shadows have dreams of being light?",
      "If the past and future exist simultaneously, are we living in a constant state of déjà vu?",
      "Do clouds ever feel self-conscious about their shape?",
      "If time is a flat circle, does that mean every bad decision we make will eventually be a good one?",
      "Are we all just characters in someone else's dream, and if so, what kind of dream is this?",
      "If the moon didn’t exist, would we all still have tides in our lives?",
      "If a potato is the key to understanding the meaning of life, how would we go about unlocking it?",
      "Can you really ‘lose’ time, or are you just borrowing it from yourself?",
      "If a thought is like a leaf floating on a river, where do the leaves go when the river dries up?",
      "If every decision creates a new reality, are we living in an infinite number of worlds or just one really confusing one?",
      "What if all the answers to life's big questions are hidden in the spaces between words?",
      "If we all speak in metaphors, does that mean we’re all living in one big metaphor?",
      "Can a fish ever truly understand water, or does it only know how to swim through it?",
      "Is silence just a sound we haven’t figured out how to hear yet?",
      "Do we really see what we see, or do we just see what we want to believe?",
      "If your reflection could talk back to you, would it tell you the truth or just repeat everything you’ve ever said?",
      "Are we living in a world of endless possibilities, or is everything just a series of improbabilities?",
      "If we could hear the thoughts of the stars, would they sound like whispers or like a grand symphony?",
      "If the sun never set, would we ever appreciate the beauty of night?",
      "What happens when you think so hard you forget what you were thinking about?",
      "If a dream is a reality that doesn’t exist, is reality a dream that we simply haven’t woken up from?",
      "If you could rewrite the laws of nature, would you change gravity, or leave it just to keep things interesting?",
      "Are you the person you think you are, or are you the person everyone else thinks you are?",
    ],
  },
};

export default writingPrompts;
